apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-dashboard
  namespace: kyverno-dashboard
  labels:
    app.kubernetes.io/name: kyverno-dashboard
    app.kubernetes.io/component: serviceaccount
