apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyverno-dashboard

resources:
  - 01-namespace.yaml
  - 02-serviceaccount.yaml
  - 03-clusterrole.yaml
  - 04-clusterrolebinding.yaml
  - 05-deployment-backend.yaml
  - 06-deployment-frontend.yaml
  - 07-service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kyverno-dashboard
      app.kubernetes.io/version: "1.0.0"
    includeSelectors: false
